/**
 * LocationIQ
 * LocationIQ provides flexible enterprise-grade location based solutions. We work with developers, startups and enterprises worldwide serving billions of requests everyday. This page provides an overview of the technical aspects of our API and will help you get started.
 *
 * The version of the OpenAPI document: 1.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIDirections_matrix_sources.h
 *
 * 
 */

#ifndef OAIDirections_matrix_sources_H
#define OAIDirections_matrix_sources_H

#include <QJsonObject>

#include <QList>
#include <QString>

#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {

class OAIDirections_matrix_sources : public OAIObject {
public:
    OAIDirections_matrix_sources();
    OAIDirections_matrix_sources(QString json);
    ~OAIDirections_matrix_sources() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    double getDistance() const;
    void setDistance(const double &distance);

    QList<double> getLocation() const;
    void setLocation(const QList<double> &location);

    QString getName() const;
    void setName(const QString &name);

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    double distance;
    bool m_distance_isSet;
    bool m_distance_isValid;

    QList<double> location;
    bool m_location_isSet;
    bool m_location_isValid;

    QString name;
    bool m_name_isSet;
    bool m_name_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAIDirections_matrix_sources)

#endif // OAIDirections_matrix_sources_H
