/**
 * LocationIQ
 * LocationIQ provides flexible enterprise-grade location based solutions. We work with developers, startups and enterprises worldwide serving billions of requests everyday. This page provides an overview of the technical aspects of our API and will help you get started.
 *
 * The version of the OpenAPI document: 1.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIDirections_directions.h
 *
 * 
 */

#ifndef OAIDirections_directions_H
#define OAIDirections_directions_H

#include <QJsonObject>

#include "OAIDirections_directions_routes.h"
#include "OAIObject.h"
#include <QList>
#include <QString>

#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {

class OAIDirections_directions : public OAIObject {
public:
    OAIDirections_directions();
    OAIDirections_directions(QString json);
    ~OAIDirections_directions() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    QString getCode() const;
    void setCode(const QString &code);

    QList<OAIObject> getWaypoints() const;
    void setWaypoints(const QList<OAIObject> &waypoints);

    QList<OAIDirections_directions_routes> getRoutes() const;
    void setRoutes(const QList<OAIDirections_directions_routes> &routes);

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    QString code;
    bool m_code_isSet;
    bool m_code_isValid;

    QList<OAIObject> waypoints;
    bool m_waypoints_isSet;
    bool m_waypoints_isValid;

    QList<OAIDirections_directions_routes> routes;
    bool m_routes_isSet;
    bool m_routes_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAIDirections_directions)

#endif // OAIDirections_directions_H
