/**
 * LocationIQ
 * LocationIQ provides flexible enterprise-grade location based solutions. We work with developers, startups and enterprises worldwide serving billions of requests everyday. This page provides an overview of the technical aspects of our API and will help you get started.
 *
 * The version of the OpenAPI document: 1.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIDirections_directions_routes.h
 *
 * 
 */

#ifndef OAIDirections_directions_routes_H
#define OAIDirections_directions_routes_H

#include <QJsonObject>

#include "OAIObject.h"
#include <QList>
#include <QString>

#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {

class OAIDirections_directions_routes : public OAIObject {
public:
    OAIDirections_directions_routes();
    OAIDirections_directions_routes(QString json);
    ~OAIDirections_directions_routes() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    QList<OAIObject> getLegs() const;
    void setLegs(const QList<OAIObject> &legs);

    QString getWeightName() const;
    void setWeightName(const QString &weight_name);

    QString getGeometry() const;
    void setGeometry(const QString &geometry);

    double getWeight() const;
    void setWeight(const double &weight);

    double getDistance() const;
    void setDistance(const double &distance);

    double getDuration() const;
    void setDuration(const double &duration);

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    QList<OAIObject> legs;
    bool m_legs_isSet;
    bool m_legs_isValid;

    QString weight_name;
    bool m_weight_name_isSet;
    bool m_weight_name_isValid;

    QString geometry;
    bool m_geometry_isSet;
    bool m_geometry_isValid;

    double weight;
    bool m_weight_isSet;
    bool m_weight_isValid;

    double distance;
    bool m_distance_isSet;
    bool m_distance_isValid;

    double duration;
    bool m_duration_isSet;
    bool m_duration_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAIDirections_directions_routes)

#endif // OAIDirections_directions_routes_H
