/**
 * LocationIQ
 * LocationIQ provides flexible enterprise-grade location based solutions. We work with developers, startups and enterprises worldwide serving billions of requests everyday. This page provides an overview of the technical aspects of our API and will help you get started.
 *
 * The version of the OpenAPI document: 1.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIDirections_matrix.h
 *
 * 
 */

#ifndef OAIDirections_matrix_H
#define OAIDirections_matrix_H

#include <QJsonObject>

#include "OAIDirections_matrix_sources.h"
#include <QList>
#include <QString>

#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {

class OAIDirections_matrix : public OAIObject {
public:
    OAIDirections_matrix();
    OAIDirections_matrix(QString json);
    ~OAIDirections_matrix() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    QString getCode() const;
    void setCode(const QString &code);

    QList<double> getDistances() const;
    void setDistances(const QList<double> &distances);

    QList<double> getFallbackSpeedCells() const;
    void setFallbackSpeedCells(const QList<double> &fallback_speed_cells);

    QList<OAIDirections_matrix_sources> getSources() const;
    void setSources(const QList<OAIDirections_matrix_sources> &sources);

    QList<OAIDirections_matrix_sources> getDestinations() const;
    void setDestinations(const QList<OAIDirections_matrix_sources> &destinations);

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    QString code;
    bool m_code_isSet;
    bool m_code_isValid;

    QList<double> distances;
    bool m_distances_isSet;
    bool m_distances_isValid;

    QList<double> fallback_speed_cells;
    bool m_fallback_speed_cells_isSet;
    bool m_fallback_speed_cells_isValid;

    QList<OAIDirections_matrix_sources> sources;
    bool m_sources_isSet;
    bool m_sources_isValid;

    QList<OAIDirections_matrix_sources> destinations;
    bool m_destinations_isSet;
    bool m_destinations_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAIDirections_matrix)

#endif // OAIDirections_matrix_H
