/**
 * LocationIQ
 * LocationIQ provides flexible enterprise-grade location based solutions. We work with developers, startups and enterprises worldwide serving billions of requests everyday. This page provides an overview of the technical aspects of our API and will help you get started.
 *
 * The version of the OpenAPI document: 1.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIDirections_matching.h
 *
 * 
 */

#ifndef OAIDirections_matching_H
#define OAIDirections_matching_H

#include <QJsonObject>

#include "OAIObject.h"
#include <QList>
#include <QString>

#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {

class OAIDirections_matching : public OAIObject {
public:
    OAIDirections_matching();
    OAIDirections_matching(QString json);
    ~OAIDirections_matching() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    QString getCode() const;
    void setCode(const QString &code);

    QList<OAIObject> getTracepoints() const;
    void setTracepoints(const QList<OAIObject> &tracepoints);

    QList<OAIObject> getMatchings() const;
    void setMatchings(const QList<OAIObject> &matchings);

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    QString code;
    bool m_code_isSet;
    bool m_code_isValid;

    QList<OAIObject> tracepoints;
    bool m_tracepoints_isSet;
    bool m_tracepoints_isValid;

    QList<OAIObject> matchings;
    bool m_matchings_isSet;
    bool m_matchings_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAIDirections_matching)

#endif // OAIDirections_matching_H
